apiVersion: v2
name: tdarr-wrapper
description: Wrapper chart for Tdarr (CPU-only transcoding)
type: application
version: 0.1.0
appVersion: "2.21.01"
dependencies:
  - name: app-template
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts/
