---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: readmebook-main
  namespace: media
spec:
  name: readmebook_main
  owner: readmebook
  ensure: present
  cluster:
    name: arrs-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: readmebook-log
  namespace: media
spec:
  name: readmebook_log
  owner: readmebook
  ensure: present
  cluster:
    name: arrs-pg
