apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-pg-creds
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: seerr-pg
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
        db: "{{ `{{ .db }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: postgres/seerr
        property: username
    - secretKey: password
      remoteRef:
        key: postgres/seerr
        property: password
    - secretKey: db
      remoteRef:
        key: postgres/seerr
        property: db
