apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-pg-creds
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: sonarr-pg
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
        main_db: "{{ `{{ .main_db }}` }}"
        log_db: "{{ `{{ .log_db }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: postgres/sonarr
        property: username
    - secretKey: password
      remoteRef:
        key: postgres/sonarr
        property: password
    - secretKey: main_db
      remoteRef:
        key: postgres/sonarr
        property: main_db
    - secretKey: log_db
      remoteRef:
        key: postgres/sonarr
        property: log_db
