---
- name: Install Box64
  ansible.builtin.import_tasks: box64.yml

- name: Install Valheim dedicated server
  ansible.builtin.import_tasks: install.yml

- name: Open host firewall for Valheim
  ansible.builtin.import_tasks: firewall.yml

- name: Install BepInEx and mods
  ansible.builtin.import_tasks: bepinex.yml

- name: Configure and start valheim service
  ansible.builtin.import_tasks: service.yml

- name: Configure world backups
  ansible.builtin.import_tasks: backup.yml
