apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scraparr-apikeys
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: scraparr-apikeys
    creationPolicy: Owner
  data:
    - secretKey: sonarr
      remoteRef:
        key: scraparr/api-keys
        property: sonarr
    - secretKey: radarr
      remoteRef:
        key: scraparr/api-keys
        property: radarr
    - secretKey: seerr
      remoteRef:
        key: scraparr/api-keys
        property: seerr
