apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tautulli-exporter
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: tautulli-exporter
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: tautulli/exporter
        property: api-key
