apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmalert-ha-webhook
  namespace: vm-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: vmalert-ha-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: secret/vmalert/ha-webhook
        property: url
