apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nzbget-credentials
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: nzbget-credentials
    creationPolicy: Owner
  data:
    - secretKey: provider-host
      remoteRef:
        key: nzbget/credentials
        property: provider-host
    - secretKey: provider-username
      remoteRef:
        key: nzbget/credentials
        property: provider-username
    - secretKey: provider-password
      remoteRef:
        key: nzbget/credentials
        property: provider-password
    - secretKey: control-password
      remoteRef:
        key: nzbget/credentials
        property: control-password
