---
- name: Update GRUB
  ansible.builtin.command: update-grub
  changed_when: true
  notify:
    - Prompt reboot

- name: Refresh Proxmox boot tool
  ansible.builtin.command: proxmox-boot-tool refresh
  changed_when: true
  notify:
    - Prompt reboot

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u -k all
  changed_when: true
  notify:
    - Prompt reboot

- name: Prompt reboot
  ansible.builtin.debug:
    msg: "A system reboot is required for IOMMU and VFIO changes to take effect."

- name: Bring up vmbr1
  ansible.builtin.command: ifup vmbr1
  changed_when: true
