apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: nzbget-exporter
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nzbget-exporter
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
