apiVersion: v2
name: seerr-wrapper
description: Wrapper chart for Seerr (request UI; consolidation of Overseerr+Jellyseerr)
type: application
version: 0.2.0
appVersion: "latest"
dependencies:
  - name: app-template
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts/
