apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-exporter
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: plex-exporter
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: plex/exporter
        property: token
