apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmsingle-chalupa
  namespace: vm-system
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  retentionPeriod: "30d"
  replicaCount: 1
  storage:
    accessModes: [ReadWriteOnce]
    storageClassName: local-path
    resources:
      requests:
        storage: 40Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /health
      port: 8429
    timeoutSeconds: 5
    periodSeconds: 30
  readinessProbe:
    httpGet:
      path: /health
      port: 8429
    timeoutSeconds: 5
    periodSeconds: 10
